#!/bin/bash

# Script d'aide pour configurer Keycloak
# Ce script démarre Keycloak et affiche les instructions de configuration

echo "=========================================="
echo "Configuration Keycloak pour MCP OAuth2"
echo "=========================================="
echo ""
echo "1. Démarrer Keycloak avec Docker:"
echo "   docker run -p 9000:8080 \\"
echo "     -e KEYCLOAK_ADMIN=admin \\"
echo "     -e KEYCLOAK_ADMIN_PASSWORD=admin \\"
echo "     quay.io/keycloak/keycloak:26.0 start-dev"
echo ""
echo "2. Accéder à l'interface Keycloak:"
echo "   http://localhost:9000"
echo "   Login: admin / admin"
echo ""
echo "3. Créer un nouveau Realm:"
echo "   - Cliquer sur le menu déroulant en haut à gauche"
echo "   - Sélectionner 'Create Realm'"
echo "   - Nom: mcp-realm"
echo ""
echo "4. Créer un Client:"
echo "   - Aller dans 'Clients' > 'Create client'"
echo "   - Client ID: mcp-client"
echo "   - Client authentication: ON"
echo "   - Valid redirect URIs: http://localhost:8081/*"
echo "   - Web origins: http://localhost:8081"
echo ""
echo "5. Configurer les Credentials:"
echo "   - Aller dans l'onglet 'Credentials' du client"
echo "   - Copier le 'Client secret' (par défaut: secret)"
echo ""
echo "6. Créer les Client Scopes:"
echo "   - Aller dans 'Client scopes' > 'Create client scope'"
echo "   - Créer 'mcp:read'"
echo "   - Créer 'mcp:write'"
echo ""
echo "7. Assigner les scopes au client:"
echo "   - Aller dans le client 'mcp-client' > onglet 'Client scopes'"
echo "   - Ajouter 'mcp:read' et 'mcp:write' aux 'Default Client Scopes'"
echo ""
echo "=========================================="
echo "Configuration terminée!"
echo "=========================================="

